[mypy]
python_version = 3.12
ignore_missing_imports = True
check_untyped_defs = True
warn_unused_ignores = True
warn_return_any = True
files = core, ui, hooks, services, bootstrap, main.py
exclude = (?x)(
    dist/
    | build/
    | temp_icons/
    | plugins/
    | tests/
  )

[mypy-ui.*]
check_untyped_defs = False

[mypy-tests.*]
check_untyped_defs = False
