"""Base widget styles — QWidget/QLabel/QToolTip defaults."""

_BASE_DARK = (
    "\n"
    "                QWidget {\n"
    "                    background: transparent;\n"
    "                    color: rgba(255, 255, 255, 0.9);\n"
    "                    font-size: 13px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "                QLabel {\n"
    "                    background: transparent;\n"
    "                    color: rgba(255, 255, 255, 0.9);\n"
    "                    font-size: 13px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "                QPushButton {\n"
    "                    font-size: 13px;\n"
    "                    font-weight: 400;\n"
    "                    padding: 0px;\n"
    "                    text-align: center;\n"
    "                }\n"
    "                QLineEdit, QTextEdit, QPlainTextEdit {\n"
    "                    font-size: 13px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "                QCheckBox, QRadioButton {\n"
    "                    font-size: 13px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "                QComboBox {\n"
    "                    font-size: 13px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "                QListWidget {\n"
    "                    font-size: 13px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "                QToolTip {\n"
    "                    background: rgba(44, 44, 48, 240);\n"
    "                    color: #ffffff;\n"
    "                    border: 1px solid rgba(255, 255, 255, 0.15);\n"
    "                    border-radius: 6px;\n"
    "                    padding: 4px 8px;\n"
    "                    font-size: 11px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "                QScrollArea {\n"
    "                    border-radius: 0; border: none;\n"
    "                    background: transparent;\n"
    "                }\n"
    "                QStatusBar {\n"
    "                    background: transparent;\n"
    "                    color: rgba(142, 142, 147, 0.8);\n"
    "                    font-size: 11px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "            "
)

_BASE_LIGHT = (
    "\n"
    "                QWidget {\n"
    "                    background: transparent;\n"
    "                    color: rgba(28, 28, 30, 0.9);\n"
    "                    font-size: 13px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "                QLabel {\n"
    "                    background: transparent;\n"
    "                    color: rgba(28, 28, 30, 0.9);\n"
    "                    font-size: 13px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "                QPushButton {\n"
    "                    font-size: 13px;\n"
    "                    font-weight: 400;\n"
    "                    padding: 0px;\n"
    "                    text-align: center;\n"
    "                }\n"
    "                QLineEdit, QTextEdit, QPlainTextEdit {\n"
    "                    font-size: 13px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "                QCheckBox, QRadioButton {\n"
    "                    font-size: 13px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "                QComboBox {\n"
    "                    font-size: 13px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "                QListWidget {\n"
    "                    font-size: 13px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "                QToolTip {\n"
    "                    background: rgba(255, 255, 255, 240);\n"
    "                    color: #1c1c1e;\n"
    "                    border: 1px solid rgba(0, 0, 0, 0.1);\n"
    "                    border-radius: 6px;\n"
    "                    padding: 4px 8px;\n"
    "                    font-size: 11px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "                QScrollArea {\n"
    "                    border-radius: 0; border: none;\n"
    "                    background: transparent;\n"
    "                }\n"
    "                QStatusBar {\n"
    "                    background: transparent;\n"
    "                    color: rgba(142, 142, 147, 0.8);\n"
    "                    font-size: 11px;\n"
    "                    font-weight: 400;\n"
    "                }\n"
    "            "
)


def get_plain_style(theme: str) -> str:
    return _BASE_DARK if theme == "dark" else _BASE_LIGHT
