"""Built-in command registration catalog."""

from __future__ import annotations

from .command_registry import CommandDefinition, CommandParam
from .commands import (
    cmd_base64,
    cmd_cidr,
    cmd_clean_cache,
    cmd_clip,
    cmd_color,
    cmd_config_repair,
    cmd_conflict,
    cmd_copy_path,
    cmd_dns,
    cmd_env,
    cmd_explorer,
    cmd_git,
    cmd_god,
    cmd_hash,
    cmd_hosts,
    cmd_ip,
    cmd_json,
    cmd_jwt,
    cmd_netdiag,
    cmd_path_audit,
    cmd_plugin_list,
    cmd_plugin_new,
    cmd_plugin_reload,
    cmd_port,
    cmd_process,
    cmd_qr,
    cmd_selected,
    cmd_sysreport,
    cmd_timestamp,
    cmd_tls,
    cmd_urlencode,
    cmd_uuid,
    cmd_wifi,
)

PANEL_COMMAND_IDS = {
    "uuid",
    "timestamp",
    "base64",
    "urlencode",
    "color",
    "ip",
    "copy-path",
    "hash",
    "qr",
    "json",
    "jwt",
    "netdiag",
    "cidr",
    "tls",
    "path-audit",
    "process",
    "sysreport",
    "plugin-list",
    "plugin-new",
    "wifi",
    "port",
    "conflict",
    "clean-cache",
    "config-repair",
    "git",
    "selected",
    "clip",
    "env",
    "god",
}


def build_builtin_command_definitions() -> list[CommandDefinition]:
    """Return fresh CommandDefinition objects for built-in commands."""
    return [
        CommandDefinition(
            id="uuid",
            title="UUID",
            aliases=["uuid", "guid"],
            description="生成 UUID / GUID",
            category="developer",
            handler=cmd_uuid,
        ),
        CommandDefinition(
            id="timestamp",
            title="时间戳",
            aliases=["timestamp", "ts", "时间戳"],
            description="当前 Unix 时间戳",
            category="developer",
            handler=cmd_timestamp,
        ),
        CommandDefinition(
            id="base64",
            title="Base64",
            aliases=["base64", "b64"],
            description="Base64 编码 / 解码",
            category="developer",
            handler=cmd_base64,
        ),
        CommandDefinition(
            id="urlencode",
            title="URL 编码",
            aliases=["urlencode", "url", "urldecode"],
            description="URL 编码 / 解码",
            category="developer",
            handler=cmd_urlencode,
        ),
        CommandDefinition(
            id="color",
            title="颜色",
            aliases=["color", "colour", "颜色", "hex"],
            description="颜色代码转换",
            category="developer",
            handler=cmd_color,
        ),
        CommandDefinition(
            id="ip",
            title="IP",
            aliases=["ip", "本机ip", "内网ip", "公网ip", "wanip"],
            description="查询当前内网 IP 与公网 IP",
            category="network",
            handler=cmd_ip,
        ),
        CommandDefinition(
            id="copy-path",
            title="复制路径",
            aliases=["copy-path", "copypath", "复制路径"],
            description="复制当前路径",
            category="system",
            handler=cmd_copy_path,
        ),
        CommandDefinition(
            id="hash",
            title="Hash",
            aliases=["hash", "哈希"],
            description="计算文本哈希",
            category="developer",
            handler=cmd_hash,
            params=[
                CommandParam(
                    name="file",
                    type="file",
                    required=True,
                    source="selected_file",
                    label="文件",
                    validator="file",
                ),
                CommandParam(
                    name="algorithm",
                    type="choice",
                    default="sha256",
                    choices=["md5", "sha1", "sha256", "sha512"],
                    label="算法",
                ),
            ],
        ),
        CommandDefinition(
            id="qr",
            title="二维码",
            aliases=["qr", "qrcode", "二维码"],
            description="生成 QR 二维码",
            category="developer",
            handler=cmd_qr,
        ),
        CommandDefinition(
            id="json",
            title="JSON 工具",
            aliases=["json", "json-format", "jsonfmt", "json美化", "json压缩"],
            description="JSON 格式化、压缩与校验",
            category="developer",
            handler=cmd_json,
            params=[
                CommandParam(name="text", type="textarea", source="clipboard", label="JSON", multiline=True),
                CommandParam(
                    name="mode",
                    type="choice",
                    default="format",
                    choices=["format", "minify", "validate"],
                    label="模式",
                ),
            ],
        ),
        CommandDefinition(
            id="jwt",
            title="JWT 解码",
            aliases=["jwt", "jwt-decode", "token"],
            description="解码 JWT Header 与 Payload（不验证签名）",
            category="developer",
            handler=cmd_jwt,
            params=[CommandParam(name="token", type="textarea", source="clipboard", label="Token", multiline=True)],
        ),
        CommandDefinition(
            id="netdiag",
            title="网络诊断",
            aliases=["netdiag", "net", "网络诊断", "连通性"],
            description="诊断 DNS、TCP 端口与 Ping 延迟",
            category="network",
            handler=cmd_netdiag,
        ),
        CommandDefinition(
            id="cidr",
            title="CIDR 子网计算",
            aliases=["cidr", "subnet", "子网", "网段"],
            description="计算网段、掩码、广播地址与可用地址范围",
            category="network",
            handler=cmd_cidr,
        ),
        CommandDefinition(
            id="tls",
            title="TLS 证书检查",
            aliases=["tls", "cert", "certificate", "ssl", "证书"],
            description="检查域名 TLS 协议、证书颁发者与到期时间",
            category="network",
            handler=cmd_tls,
            params=[
                CommandParam(name="host", type="text", required=True, label="域名", validator="domain"),
                CommandParam(name="port", type="number", default="443", label="端口", validator="port"),
            ],
        ),
        CommandDefinition(
            id="path-audit",
            title="PATH 体检",
            aliases=["path-audit", "path", "env-path", "环境变量", "path体检"],
            description="检查 PATH 失效目录、重复目录和常用命令遮蔽",
            category="developer",
            handler=cmd_path_audit,
        ),
        CommandDefinition(
            id="process",
            title="进程分析",
            aliases=["process", "proc", "ps", "进程"],
            description="查看高占用进程、搜索进程或按 PID 终止",
            category="system",
            handler=cmd_process,
        ),
        CommandDefinition(
            id="sysreport",
            title="系统快照",
            aliases=["sysreport", "sys", "system-report", "系统快照"],
            description="汇总 CPU、内存、磁盘、网络与启动时间",
            category="system",
            handler=cmd_sysreport,
        ),
        CommandDefinition(
            id="plugin-list",
            title="插件列表",
            aliases=["plugin-list", "plugins", "插件列表"],
            description="列出已加载的插件",
            category="plugin",
            handler=cmd_plugin_list,
        ),
        CommandDefinition(
            id="plugin-reload",
            title="重载插件",
            aliases=["plugin-reload", "preload"],
            description="重新加载插件",
            category="plugin",
            handler=cmd_plugin_reload,
        ),
        CommandDefinition(
            id="plugin-new",
            title="新建插件",
            aliases=["plugin-new", "pnew"],
            description="创建插件模板",
            category="plugin",
            handler=cmd_plugin_new,
        ),
        CommandDefinition(
            id="wifi",
            title="Wi-Fi 密码查询",
            aliases=[
                "wifi",
                "wlan",
                "无线密码",
                "Wi-Fi 密码查询",
                "Wi-Fi",
                "wi-fi",
                "wifi密码",
                "wifi密码查询",
            ],
            description="查询已保存的 Wi-Fi 密码",
            category="system",
            handler=cmd_wifi,
        ),
        CommandDefinition(
            id="hosts",
            title="编辑 Hosts 文件",
            aliases=["hosts", "host"],
            description="打开 Hosts 文件进行编辑",
            category="system",
            handler=cmd_hosts,
        ),
        CommandDefinition(
            id="port",
            title="端口占用查询",
            aliases=["port", "端口", "netstat"],
            description="查询端口占用情况",
            category="developer",
            handler=cmd_port,
            params=[
                CommandParam(name="port", type="number", required=True, label="端口", validator="port"),
                CommandParam(name="action", type="choice", default="query", choices=["query", "kill"], label="动作"),
            ],
        ),
        CommandDefinition(
            id="dns",
            title="清理 DNS 缓存",
            aliases=["dns", "flushdns", "清理dns"],
            description="清理 DNS 缓存",
            category="network",
            handler=cmd_dns,
        ),
        CommandDefinition(
            id="clean-cache",
            title="清理缓存",
            aliases=["clean-cache", "cache-clean", "clear-cache", "清理缓存", "缓存清理"],
            description="清理项目目录下未使用的临时缓存",
            category="internal",
            handler=cmd_clean_cache,
        ),
        CommandDefinition(
            id="config-repair",
            title="配置修复",
            aliases=["config-repair", "repair-config", "config-fix", "配置修复", "旧配置修复"],
            description="扫描或修复旧版本配置变量语法",
            category="system",
            handler=cmd_config_repair,
        ),
        CommandDefinition(
            id="explorer",
            title="重启资源管理器",
            aliases=["explorer", "重启资源管理器", "restart-explorer"],
            description="重启 Windows 资源管理器",
            category="system",
            handler=cmd_explorer,
        ),
        CommandDefinition(
            id="conflict",
            title="热键冲突检查",
            aliases=["conflict", "冲突", "hotkey-conflict"],
            description="检查快捷键冲突",
            category="system",
            handler=cmd_conflict,
        ),
        CommandDefinition(
            id="git",
            title="Git",
            aliases=["git", "git-status", "git-pull", "git-checkout"],
            description="Git status/branch/log/diff/fetch/pull/checkout",
            category="developer",
            handler=cmd_git,
            result_window_size="large",
        ),
        CommandDefinition(
            id="selected",
            title="选中文字",
            aliases=["selected", "sel", "选中", "选中文字"],
            description="显示当前选中文字信息",
            category="system",
            handler=cmd_selected,
        ),
        CommandDefinition(
            id="clip",
            title="剪贴板",
            aliases=["clip", "clipboard", "剪贴板"],
            description="显示剪贴板内容与类型",
            category="system",
            handler=cmd_clip,
        ),
        CommandDefinition(
            id="env",
            title="环境变量",
            aliases=["env", "environment", "环境变量", "环境变量编辑", "编辑环境变量"],
            description="打开 Windows 系统环境变量编辑器",
            category="system",
            handler=cmd_env,
        ),
        CommandDefinition(
            id="god",
            title="上帝模式",
            aliases=["god", "godmode", "god-mode", "上帝模式"],
            description="打开 Windows 上帝模式 (God Mode) 文件夹",
            category="system",
            handler=cmd_god,
        ),
    ]
